/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // 稷下青铜机关城主题色 - 防止被purge
    'text-jixia-gold',
    'text-jixia-orange',
    'text-jixia-jade',
    'text-jixia-star',
    'text-jixia-bronze',
    'text-jixia-red',
    'text-jixia-bamboo',
    'text-jixia-ink',
    'border-jixia-gold',
    'border-jixia-orange',
    'border-jixia-jade',
    'border-jixia-star',
    'border-jixia-bronze',
    'border-jixia-red',
    'bg-jixia-gold',
    'bg-jixia-orange',
    'bg-jixia-jade',
    'bg-jixia-star',
    'bg-jixia-bronze',
    'bg-jixia-red',
    'bg-jixia-bg',
    'bg-jixia-black',
    // 透明度变体
    'border-jixia-gold/30',
    'border-jixia-gold/50',
    'border-jixia-orange/30',
    'border-jixia-jade/30',
    'border-jixia-star/30',
    'border-jixia-bronze/20',
    'border-jixia-bronze/40',
    'text-jixia-bamboo/60',
    'text-jixia-bamboo/80',
    'bg-jixia-gold/10',
    'bg-jixia-gold/50',
  ],
  theme: {
    extend: {
      colors: {
        'battle-bg': '#1a1a2e',
        'battle-board': '#16213e',
        'debug-box': '#e94560',
        'battle-border': '#7a5a34',
        'battle-border-light': 'rgba(184,136,84,0.45)',
        'battle-border-medium': 'rgba(184,136,84,0.5)',
        'battle-gold': '#b88a53',
        // 稷下青铜机关城主题色
        'jixia-bg': '#1a0f05',
        'jixia-bronze': '#5c3a21',
        'jixia-patina': '#4a5d4e',
        'jixia-jade': '#4ade80',
        'jixia-star': '#4dabff',
        'jixia-orange': '#ff6600',
        'jixia-red': '#8b0000',
        'jixia-gold': '#d4a017',
        'jixia-bamboo': '#e0d5c1',
        'jixia-black': '#0a0503',
        'jixia-ink': '#1c1c1c',
        // theme colors
        'theme-primary': 'var(--color-primary)',
        'theme-primary-light': 'var(--color-primary-light)',
        'theme-primary-dark': 'var(--color-primary-dark)',
        'theme-secondary': 'var(--color-secondary)',
        'theme-secondary-light': 'var(--color-secondary-light)',
        'theme-accent': 'var(--color-accent)',
        'theme-accent-light': 'var(--color-accent-light)',
        'theme-background': 'var(--color-background)',
        'theme-background-light': 'var(--color-background-light)',
        'theme-background-dark': 'var(--color-background-dark)',
        'theme-surface': 'var(--color-surface)',
        'theme-surface-light': 'var(--color-surface-light)',
        'theme-surface-dark': 'var(--color-surface-dark)',
        'theme-text': 'var(--color-text)',
        'theme-text-muted': 'var(--color-text-muted)',
        'theme-text-light': 'var(--color-text-light)',
        'theme-border': 'var(--color-border)',
        'theme-border-light': 'var(--color-border-light)',
        'theme-success': 'var(--color-success)',
        'theme-warning': 'var(--color-warning)',
        'theme-danger': 'var(--color-danger)',
        'theme-info': 'var(--color-info)',
        'theme-gold': 'var(--color-gold)',
        'theme-gold-light': 'var(--color-gold-light)',
        'theme-gold-dark': 'var(--color-gold-dark)',
      },
      backgroundImage: {
        'theme-primary': 'var(--gradient-primary)',
        'theme-secondary': 'var(--gradient-secondary)',
        'theme-accent': 'var(--gradient-accent)',
        'theme-surface': 'var(--gradient-surface)',
        'theme-card': 'var(--gradient-card)',
        'theme-hero': 'var(--gradient-hero)',
        'theme-enemy': 'var(--gradient-enemy)',
      },
      boxShadow: {
        'theme-primary': 'var(--shadow-primary)',
        'theme-glow': 'var(--shadow-glow)',
        'theme-card': 'var(--shadow-card)',
        'theme-elevated': 'var(--shadow-elevated)',
        'card-glow': '0 0 20px rgba(201, 149, 42, 0.3)',
        'card-glow-strong': '0 0 30px rgba(201, 149, 42, 0.5)',
        'damage': '0 0 15px rgba(201, 114, 90, 0.5)',
        'heal': '0 0 15px rgba(90, 201, 114, 0.5)',
        'mana': '0 0 15px rgba(90, 149, 201, 0.5)',
      },
      animation: {
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'fade-in-up': 'fade-in-up 0.3s ease-out',
        'fade-in-down': 'fade-in-down 0.3s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
        'scale-in-bounce': 'scale-in-bounce 0.4s ease-out',
        'slide-in-left': 'slide-in-left 0.3s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'slide-in-up': 'slide-in-up 0.3s ease-out',
        'slide-in-down': 'slide-in-down 0.3s ease-out',
        'card-draw': 'card-draw 0.5s ease-out',
        'card-play': 'card-play 0.3s ease-out',
        'card-discard': 'card-discard 0.3s ease-out',
        'attack-shake': 'attack-shake 0.3s ease-in-out',
        'damage-flash': 'damage-flash 0.2s ease-in-out',
        'heal-pulse': 'heal-pulse 0.5s ease-in-out',
        'phase-transition': 'phase-transition 0.5s ease-in-out',
        'spin-slow': 'spin 3s linear infinite',
        'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
        'bounce-subtle': 'bounce-subtle 0.5s ease-in-out',
      },
      keyframes: {
        'glow-pulse': {
          '0%, 100%': { 
            boxShadow: 'var(--shadow-primary)',
            opacity: '1',
          },
          '50%': { 
            boxShadow: 'var(--shadow-glow)',
            opacity: '0.9',
          },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'scale-in-bounce': {
          '0%': { opacity: '0', transform: 'scale(0.8)' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-right': {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-down': {
          '0%': { opacity: '0', transform: 'translateY(-30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'card-draw': {
          '0%': { opacity: '0', transform: 'translateY(100px) rotateY(180deg)' },
          '100%': { opacity: '1', transform: 'translateY(0) rotateY(0)' },
        },
        'card-play': {
          '0%': { transform: 'scale(1) translateY(0)' },
          '50%': { transform: 'scale(1.1) translateY(-30px)' },
          '100%': { opacity: '0', transform: 'scale(0.8) translateY(-60px)' },
        },
        'card-discard': {
          '0%': { opacity: '1', transform: 'translateX(0) rotate(0)' },
          '100%': { opacity: '0', transform: 'translateX(100px) rotate(10deg)' },
        },
        'attack-shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-5px)' },
          '75%': { transform: 'translateX(5px)' },
        },
        'damage-flash': {
          '0%, 100%': { filter: 'brightness(1)' },
          '50%': { filter: 'brightness(1.5) saturate(1.2)' },
        },
        'heal-pulse': {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(90, 201, 114, 0.4)' },
          '50%': { transform: 'scale(1.02)', boxShadow: '0 0 20px 5px rgba(90, 201, 114, 0.2)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(90, 201, 114, 0)' },
        },
        'phase-transition': {
          '0%': { opacity: '0', transform: 'scale(0.5)' },
          '50%': { opacity: '1', transform: 'scale(1.1)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'bounce-subtle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
      },
      transitionTimingFunction: {
        'bounce-in': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'smooth-out': 'cubic-bezier(0.23, 1, 0.32, 1)',
      },
      transitionDuration: {
        '250': '250ms',
        '350': '350ms',
        '400': '400ms',
      },
    },
  },
  plugins: [],
}
